# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  Municipality: create, read, update, delete
  IlpProposal: create, read, update, delete  
  Province: create, read, update, delete
  IlpSignature: create, read, update, delete
  EndorsmentProposal: create, read, update, delete
  EndorsmentSignature: create, read, update, delete
  Election: create, read, update, delete