# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Municipality:
  fields:
    default: id_ine, name, province_id, province
    form: id_ine, name, province_id, province
  order_by: 
  relationships: province
  filters: created_at
  search: name
  application: MiFirma
  export: csv, xml

IlpProposal:
  fields:
    default: name, handwritten_signatures, signatures_end_date, signatures.size, num_signatures_signed
    form: name, problem, howto_solve, tractis_template_code, attestor_template_code, pdf, num_required_signatures, promoter_name, promoter_url, handwritten_signatures, banner, promoter_short_name, signatures_end_date, ilp_code, user
  order_by: position
  filters: created_at
  relationships: signatures, attestors_signatures
  search: name
  application: MiFirma
  export: csv, xml

Province:
  fields:
    default: id, name, id_ine
    form: id_ine, name, only_circunscription
  order_by: 
  relationships: municipalities
  filters: created_at
  search: name
  application: MiFirma
  export: csv, xml

User:
  fields:
    default: id, name, email
    form: id, name, email
  order_by: 
  filters: created_at
  search: name
  application: MiFirma
  export: csv, xml

IlpSignature:
  fields:
    default: proposal, email, state, name, dni, surname
    form: proposal_id, email, state, token, tractis_contract_location, name, dni, surname, terms, proposal, date_of_birth, tractis_signature
  order_by: 
  relationships: proposal
  filters: created_at
  search: name
  application: MiFirma

AttestorSignature:
  fields:
    default: proposal, email, state, name, dni, surname, province, municipality
    form: proposal_id, email, state, token, tractis_contract_location, name, dni, surname, telephone, terms, province_id, municipality_id, zipcode, proposal, date_of_birth,  province_of_birth_id, municipality_of_birth_id, address, province, municipality, province_of_birth, municipality_of_birth, tractis_signature
  order_by: 
  relationships: municipality, proposal
  filters: created_at
  search: name
  application: MiFirma

EndorsmentSignature:
  fields:
    default: proposal, email, state, name, dni, surname, province
    form: proposal_id, email, state, token, tractis_contract_location, name, dni, surname, terms, province_id, proposal, date_of_birth,   province, tractis_signature
  order_by: 
  relationships: province, proposal
  filters: created_at
  search: name
  application: MiFirma

EndorsmentProposal:
  fields:
    default: name, signatures.size, num_signatures_signed
    form: name, problem, howto_solve,tractis_template_code, promoter_name, promoter_url, banner, promoter_short_name, election_type, election, user
  order_by: position
  relationships: signatures
  filters: created_at
  search: name
  application: MiFirma
  export: csv, xml

Election:
  fields:
    default: name, signatures_end_date
    form: name, signatures_end_date
  order_by: 
  relationships: endorsment_proposals
  filters: created_at
  search: name
  application: MiFirma
  export: csv, xml