# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Municipality:
  fields:
    default: id_ine, name, province_id, province
    form: id_ine, name, province_id, province
  order_by: 
  relationships: province
  filters: created_at
  search: name
  application: MiFirma

IlpProposal:
  fields:
    default: name, position, tractis_template_code, num_required_signatures, promoter_name, handwritten_signatures, signatures_end_date
    form: name, problem, howto_solve, tractis_template_code, pdf, num_required_signatures, promoter_name, promoter_url, handwritten_signatures, banner, promoter_short_name, signatures_end_date
  order_by: position
  filters: created_at
  search: name
  application: MiFirma

Province:
  fields:
    default: id_ine, name
    form: id_ine, name
  order_by: 
  relationships: municipalities
  filters: created_at
  search: name
  application: MiFirma

IlpSignature:
  fields:
    default: ilp_proposal, email, state, name, dni, surname, province, municipality
    form: proposal_id, email, state, token, tractis_contract_location, name, dni, surname, terms, province_id, municipality_id, zipcode, ilp_proposal, date_of_birth,  province_of_birth_id, municipality_of_birth_id, address, province, municipality, province_of_birth, municipality_of_birth
  order_by: 
  relationships: municipality, ilp_proposal
  filters: created_at
  search: name
  application: MiFirma

EndorsmentSignature:
  fields:
    default: endorsment_proposal, email, state, name, dni, surname, province
    form: proposal_id, email, state, token, tractis_contract_location, name, dni, surname, terms, province_id, endorsment_proposal, date_of_birth,   province
  order_by: 
  relationships: province, endorsment_proposal
  filters: created_at
  search: name
  application: MiFirma

EndorsmentProposal:
  fields:
    default: name, position, tractis_template_code, promoter_name,  signatures_end_date
    form: name, problem, howto_solve, tractis_template_code, promoter_name, promoter_url, banner, promoter_short_name, signatures_end_date, election_type
  order_by: position
  filters: created_at
  search: name
  application: MiFirma