# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Proposal:
  fields:
    list: name, position
    form: name, problem, howto_solve
  order_by: position
  relationships: 
  filters: 
  search: 
  application: mifirma

Signature:
  fields:
    list: proposal_id, created_at
    form: proposal_id
  order_by: 
  relationships: 
  filters: 
  search: 
  application: mifirma

