# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Proposal:
  fields:
    list: name, tractis_template_code, position
    form: name, problem, howto_solve, tractis_template_code
  order_by: position
  relationships: 
  filters: 
  search: 
  application: mifirma

Signature:
  fields:
    list: proposal, email, name, dni, state, created_at
    show: proposal, email, name, dni, state, created_at
  order_by: 
  relationships: 
  options:
    default_action: show
  filters: 
  search:
  application: mifirma

